config/routes.rb
Rails.application.routes.draw do
  resources :plans do
    get :new_event, on: :member
    post :continue_to_event_creation
  end
  resources :travel_events, except: :index
  resources :lodging_events, except: :index
  get '/manifesto', to: 'application#manifesto'
  get '/help', to: 'application#help'
  root to: 'application#home'
end

app/models/travel_event.rb
class TravelEvent < ApplicationRecord
  extend Enumerize

  belongs_to :plan

  enumerize :mode_of_transportation, in: [:car, :bus, :train, :bike, :walk]

  def duration_in_words
    data['routes'].first['legs'].first['duration']['text']
  end

  def duration_hash
    components = duration_in_words.split(' ')
    if duration_in_words.include? 'day'
      { days: components.first.to_i, hours: components.third.to_i }
    else
      { hours: components.first.to_i, minutes: components.third.to_i }
    end
  end
end

app/controllers/travel_events_controller.rb
class TravelEventsController < ApplicationController
  before_action :find_travel_event, except: [:new, :create]

  def new
    @travel_event = TravelEvent.new
  end

  def show
  end

  def edit
  end

  def create
    @travel_event = TravelEvent.new(travel_event_params)
    if @travel_event.save
      flash[:notice] = t('model.travel_event.created')
      redirect_to plan_path(@travel_event.plan)
    else
      flash[:alert] = @travel_event.errors.messages
      redirect_to new_travel_event_path(@travel_event, parent_event_id: @travel_event.parent_event_id)
    end
  end

  def update
    if @travel_event.update(travel_event_params)
      flash[:notice] = t('model.travel_event.updated')
      render 'show'
    else
      flash[:warning] = @travel_event.errors
      render 'edit'
    end
  end

  def destroy
    @travel_event.delete
    render @travel_event.parent_event
  end

  protected
    def travel_event_params
      params.require(:travel_event).permit(:origin, :destination, :mode_of_transportation, :data, :plan_id).merge(data: JSON.parse(params[:travel_event][:data]))
    end

    def find_travel_event
      @travel_event = TravelEvent.find(params[:id])
    end
end

app/views/travel_events/_details.html.erb
<div class="event-details travel-event-details" id="travel_event-<%= event.id %>">
  <div class="row">
    <div class="col-sm-1 icon">
      <%= fa_icon 'map-marker', class: 'text-primary display-4' %>
    </div>
    <div class="col-sm-11 text">
      <%= link_to travel_event_path(event) do %>
        <%= event.origin %> To <%= event.destination %>:
      <% end %>
      Estimated travel time: <%= event.duration_in_words %>
    </div>
  </div>
</div>

app/views/travel_events/_form.html.erb
<div class="container form-group">
  <%= simple_form_for @travel_event do |f| %>
    <div class="form-inputs">
      <%= f.hidden_field :plan_id, value: @travel_event.plan_id || params[:plan_id] %>
      <%= f.hidden_field :data %>
      <%= f.input :origin %>
      <%= f.input :destination %>
      <%= f.input :mode_of_transportation %>
    </div>
    <div class="form-actions">
      <%= f.submit class: 'btn btn-primary', id: 'create-travel-event' %>
      <%= link_to t('crud.cancel'), plans_path, class: 'btn btn-default' %>
    </div>
  <% end %>
</div>

app/views/travel_events/show.html.erb
<div class="container" id="travel_event" data-directions="<%= @travel_event.data.to_json %>">
  <div>
    <%= @travel_event.origin %> To <%= @travel_event.destination %>
  </div>
  <div>
    Estimated travel time: <%= @travel_event.duration_in_words %>
  </div>
  <div id="map">
  </div>
</div>