config/routes.rb
Rails.application.routes.draw do
  resources :plans do
    get :new_event, on: :member
    post :continue_to_event_creation
  end
  resources :travel_events, except: :index
  resources :lodging_events, except: :index
  get '/manifesto', to: 'application#manifesto'
  get '/help', to: 'application#help'
  root to: 'application#home'
end

app/views/shared/_events_list.html.erb
<table class="table events">
  <% events.each do |event| %>
    <% event_type = event.model_name.singular.split('_').first %>
    <%= render "#{event_type}_events/details", event: event %>
  <% end %>
</div>

app/views/shared/_flash.html.erb
<% flash.select { |key, value| key.in? %w(alert notice) }.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

app/views/shared/_nav.html.erb
<div class="navigation">
  <div class="row">
    <div class="col-lg-2 nav-button">
      <%= link_to t('nav.create_plan'), new_plan_path %>
    </div>
    <div class="col-lg-2 nav-button">
      <%= link_to t('nav.view_plans'), plans_path %>
    </div>
    <div class="col-lg-4 nav-middle">
      <%= link_to root_path do %>
        <%= image_tag 'logo', height: 50, width: 100 %>
      <% end %>
    </div>
    <div class="col-lg-2 nav-button">
      <%= link_to t('nav.manifesto'), '/manifesto.html' %>
    </div>
    <div class="col-lg-2 nav-button">
      <%= link_to t('nav.help'), '/help.html' %>
    </div>
  </div>
</div>

app/views/shared/_parent_event.html.erb
<tbody>
  <tr>
    <td>
      <%= link_to parent_event.title, parent_event_path(parent_event) %>
    </td>
    <td>
      <%= parent_event.kind %>
    </td>
    <td>
      <%= format_datetime (parent_event.starts_at || DateTime.current) %>
    </td>
    <td>
      <%= format_datetime (parent_event.ends_at || DateTime.current) %>
    </td>
    <td>
      <%= parent_event.price %>
    </td>
  </tr>
</tbody>