config/routes.rb
Rails.application.routes.draw do
  resources :plans do
    get :new_event, on: :member
    post :continue_to_event_creation
  end
  resources :travel_events, except: :index
  resources :lodging_events, except: :index
  get '/manifesto', to: 'application#manifesto'
  get '/help', to: 'application#help'
  root to: 'application#home'
end

app/models/plan.rb
class Plan < ApplicationRecord
  has_many :travel_events

  def total_time_in_words
    # total_time = parent_events.map(&:total_time).sum
    # days = total_time / 1.day
    # hours = (days - days.to_i) * 100
    # minutes = ((hours - hours.to_i) * 100) % 60
    # "#{days.round} days, #{hours.round} hours, and #{minutes.round} minutes"
    ""
  end

  def total_travel_time
    travel_durations = travel_events.map(&:duration_hash)
    total_days = 0.days
    total_hours = 0.hours
    total_minutes = 0.minutes

    travel_durations.each do |duration|
      total_days += duration[:days].to_i.days
      total_hours += duration[:hours].to_i.hours
      total_minutes += duration[:minutes].to_i.minutes
    end

    { days: total_days, hours: total_hours, minutes: total_minutes }
  end

  def total_price
    # parent_events.map { |parent_event| parent_event.price.to_i }.sum
    1
  end

  def events
    TravelEvent.where(plan_id: id) + LodgingEvent.where(plan_id: id)
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :find_plan, except: [:index, :create, :new, :continue_to_event_creation]

  def index
    @plans = Plan.all
  end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.create plan_params
    render 'show', plan: @plan
  end

  def show
  end

  def edit
  end

  def update
    @plan.update(plan_params)
  end

  def destroy
    @plan.delete
    redirect_to plans_path
  end

  def new_event
  end

  def continue_to_event_creation
    redirect_to send("new_#{params[:kind]}_event_path", plan_id: params[:plan_id])
  end

  protected
    def find_plan
      @plan = Plan.find(params[:id])
    end

    def plan_params
      params.require(:plan).permit(:title)
    end
end

app/views/plans/_details.html.erb
<div class="row header">
  <div class="col-xl">
    <span class="title">
      <%= link_to plan.title, plan_path(plan) %>
    </span>
  </div>
</div>
<div class="row plan-info">
  <div class="col-md">
    <%= t('model.plan.labels.total_price') %>: <%= plan.total_price %>
  </div>
  <div class="col-md">
    <%= t('model.plan.labels.total_time') %>: <%= plan.total_time_in_words %>
  </div>
  <div class="col-md">
    <%= t('model.plan.labels.start') %>: <%= format_datetime plan.events.first.try(:starts_at) %>
  </div>
  <div class="col-md">
    <%= t('model.plan.labels.end') %>: <%= format_datetime plan.events.last.try(:ends_at) %>
  </div>
</div>

app/views/plans/_form.html.erb
<div class="container form-group">
  <%= simple_form_for @plan do |f| %>
    <%= f.input :title, placeholder: t('model.plan.title_placeholder'), label: t('model.plan.title'), input_html: { class: 'form-control' } %>
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to t('crud.cancel'), plans_path, class: 'btn btn-default' %>
  <% end %>
</div>

app/views/plans/index.html.erb
<div class="container plans-list">
  <% @plans.each do |plan| %>
    <div class="row plan">
      <div class="col-md">
        <div class="float-sm-right">
          <%= link_to t('model.parent_event.add'), new_event_plan_path(plan), class: 'btn btn-primary btn-sm' %>
          <%= link_to t('crud.delete'), plan_path(plan), method: :delete, class: 'btn btn-danger btn-sm', data: { confirm: t('crud.confirm') } %>
        </div>
        <%= render 'details', plan: plan %>
      </div>
    </div>
  <% end %>
</div>

app/views/plans/new_event.html.erb
<%= form_with url: plan_continue_to_event_creation_path(plan_id: params[:id]) do |f| %>
  <%= f.hidden_field :plan_id, value: params[:id] %>
  <%= label_tag t('model.parent_event.kind_explination') %>
  <%= f.select :kind, options_for_select(ParentEvent.kind.values), { include_blank: true }, { class: 'form-control', id: 'event-kind' } %>
<% end %>

app/views/plans/show.html.erb
<div class="container plan">
  <%= link_to t('model.parent_event.add'), new_event_plan_path(@plan), class: 'btn btn-primary btn-sm' %>
  <%= render 'details', plan: @plan %>
  <%= render 'shared/events_list', events: @plan.events %>
</div>